name: android_string_convertor
description:  command-line tool to convert android xml string to arb.
version: 0.0.1
repository: https://github.com/OmarMahmoud120/android_string_convertor

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  args: ^2.3.1
  xml: ^5.3.1

dev_dependencies:
  lints: ^1.0.0
