name: android_string_convertor
description: A command-line tool to convert Android XML string resources to ARB (Application Resource Bundle) files.
version: 0.0.2
repository: https://github.com/OmarMahmoud120/android_string_convertor

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  args: ^2.6.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^1.0.0
